import type { Work } from '../types/work'

/**
 * PDF出力用の一時DOMを生成し、html2canvasでキャプチャしてjsPDFに貼り付ける。
 * jsPDFのデフォルトフォントは日本語非対応のため、テキスト直書きではなく
 * 画像化してPDFに埋め込むことで文字化けを防ぐ。
 */

function createPdfContentElement(work: Work): HTMLDivElement {
  const el = document.createElement('div')
  el.style.cssText = `
    position: fixed; left: -9999px; top: 0;
    width: 800px; padding: 48px;
    background: #fff; color: #1a1a1a;
    font-family: "Noto Sans JP", "Barlow", "Inter", sans-serif;
    font-size: 14px; line-height: 1.7;
  `

  const facts = [
    ['ジャンル', work.genre],
    ['サイト種別', work.siteType],
    ['目的', work.purpose],
    ['予算帯', work.budgetRange ?? '要見積'],
    ['期間', work.durationRange ?? '要件に応じて調整'],
    ['規模', work.scale ?? (typeof work.pageCount === 'number' ? `${work.pageCount}ページ` : '案件ごとに調整')],
    ['年', work.year ? String(work.year) : '-'],
  ]

  const factsHtml = facts.map(([k, v]) =>
    `<div style="display:flex;gap:16px;padding:6px 0;border-bottom:1px solid #eee;">
      <span style="min-width:100px;color:#888;font-size:12px;">${k}</span>
      <span style="font-weight:500;">${v}</span>
    </div>`
  ).join('')

  const techHtml = work.techStack.length > 0
    ? `<div style="display:flex;flex-wrap:wrap;gap:6px;margin-top:8px;">
        ${work.techStack.map(t => `<span style="display:inline-block;padding:3px 10px;background:#f0f0f0;border-radius:4px;font-size:12px;">${t}</span>`).join('')}
      </div>`
    : ''

  const featuresHtml = work.features && work.features.length > 0
    ? `<ul style="margin:8px 0 0;padding-left:20px;">
        ${work.features.map(f => `<li style="margin-bottom:4px;">${f}</li>`).join('')}
      </ul>`
    : ''

  el.innerHTML = `
    <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:32px;padding-bottom:16px;border-bottom:2px solid #C4A265;">
      <span style="font-size:11px;color:#999;letter-spacing:0.1em;">AKASHIKI WORKS FINDER</span>
      <span style="font-size:11px;color:#999;">${new Date().toLocaleDateString('ja-JP')}</span>
    </div>

    <h1 style="margin:0 0 8px;font-size:28px;font-weight:700;letter-spacing:-0.02em;">${work.title}</h1>
    <p style="margin:0 0 24px;color:#666;font-size:13px;">${work.genre} / ${work.siteType}</p>

    <div style="margin-bottom:24px;">
      <h2 style="font-size:15px;font-weight:600;margin:0 0 8px;color:#C4A265;">概要</h2>
      <p style="margin:0;color:#333;">${work.summary}</p>
    </div>

    ${work.challenge ? `
    <div style="margin-bottom:24px;padding:16px;background:#fafafa;border-radius:8px;border-left:3px solid #C4A265;">
      <p style="margin:0 0 4px;font-size:12px;color:#888;font-weight:600;">背景・課題</p>
      <p style="margin:0;color:#333;">${work.challenge}</p>
    </div>` : ''}

    <div style="margin-bottom:24px;">
      <h2 style="font-size:15px;font-weight:600;margin:0 0 12px;color:#C4A265;">メタ情報</h2>
      ${factsHtml}
    </div>

    ${work.techStack.length > 0 ? `
    <div style="margin-bottom:24px;">
      <h2 style="font-size:15px;font-weight:600;margin:0 0 8px;color:#C4A265;">使用技術</h2>
      ${techHtml}
    </div>` : ''}

    ${work.features && work.features.length > 0 ? `
    <div style="margin-bottom:24px;">
      <h2 style="font-size:15px;font-weight:600;margin:0 0 8px;color:#C4A265;">実装ポイント</h2>
      ${featuresHtml}
    </div>` : ''}

    ${work.designTone ? `
    <div style="margin-bottom:24px;">
      <h2 style="font-size:15px;font-weight:600;margin:0 0 8px;color:#C4A265;">デザイントーン</h2>
      <p style="margin:0;color:#333;">${work.designTone}</p>
    </div>` : ''}

    <div style="margin-top:40px;padding-top:16px;border-top:1px solid #ddd;display:flex;justify-content:space-between;color:#aaa;font-size:10px;">
      <span>Generated by AKASHIKI Works Finder</span>
      <span>AKASHIKI</span>
    </div>
  `

  return el
}

function createCompareContentElement(works: Work[]): HTMLDivElement {
  const el = document.createElement('div')
  el.style.cssText = `
    position: fixed; left: -9999px; top: 0;
    width: 1100px; padding: 48px;
    background: #fff; color: #1a1a1a;
    font-family: "Noto Sans JP", "Barlow", "Inter", sans-serif;
    font-size: 13px; line-height: 1.6;
  `

  const rows = [
    { label: 'ジャンル', getter: (w: Work) => w.genre },
    { label: 'サイト種別', getter: (w: Work) => w.siteType },
    { label: '目的', getter: (w: Work) => w.purpose },
    { label: 'ページ数', getter: (w: Work) => w.pageCount ? `${w.pageCount}ページ` : '-' },
    { label: '予算帯', getter: (w: Work) => w.budgetRange ?? '-' },
    { label: '期間', getter: (w: Work) => w.durationRange ?? '-' },
    { label: '使用技術', getter: (w: Work) => w.techStack.join(', ') },
  ]

  const headerCells = works.map(w =>
    `<th style="padding:12px;text-align:left;font-weight:600;border-bottom:2px solid #C4A265;">${w.title}</th>`
  ).join('')

  const bodyRows = rows.map((row, i) => {
    const bg = i % 2 === 0 ? '#fafafa' : '#fff'
    const cells = works.map(w =>
      `<td style="padding:10px 12px;background:${bg};">${row.getter(w)}</td>`
    ).join('')
    return `<tr>
      <td style="padding:10px 12px;background:${bg};font-weight:500;color:#888;min-width:100px;">${row.label}</td>
      ${cells}
    </tr>`
  }).join('')

  el.innerHTML = `
    <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:32px;padding-bottom:16px;border-bottom:2px solid #C4A265;">
      <span style="font-size:11px;color:#999;letter-spacing:0.1em;">AKASHIKI WORKS FINDER — 比較レポート</span>
      <span style="font-size:11px;color:#999;">${new Date().toLocaleDateString('ja-JP')}</span>
    </div>

    <h1 style="margin:0 0 24px;font-size:24px;font-weight:700;">作品比較</h1>

    <table style="width:100%;border-collapse:collapse;font-size:13px;">
      <thead>
        <tr>
          <th style="padding:12px;text-align:left;border-bottom:2px solid #C4A265;min-width:100px;"></th>
          ${headerCells}
        </tr>
      </thead>
      <tbody>${bodyRows}</tbody>
    </table>

    <div style="margin-top:40px;padding-top:16px;border-top:1px solid #ddd;color:#aaa;font-size:10px;">
      Generated by AKASHIKI Works Finder
    </div>
  `

  return el
}

async function captureAndSavePdf(
  contentEl: HTMLDivElement,
  filename: string,
  orientation: 'p' | 'l' = 'p',
): Promise<void> {
  const [html2canvasModule, jsPDFModule] = await Promise.all([
    import('html2canvas'),
    import('jspdf'),
  ])
  const html2canvas = html2canvasModule.default
  const { jsPDF } = jsPDFModule

  document.body.appendChild(contentEl)

  try {
    const canvas = await html2canvas(contentEl, {
      scale: 2,
      useCORS: true,
      backgroundColor: '#ffffff',
    })

    const imgData = canvas.toDataURL('image/png')
    const doc = new jsPDF(orientation, 'mm', 'a4')
    const pageWidth = doc.internal.pageSize.getWidth()
    const pageHeight = doc.internal.pageSize.getHeight()
    const margin = 10

    const imgWidth = pageWidth - margin * 2
    const imgHeight = (canvas.height * imgWidth) / canvas.width

    // 1ページに収まらない場合は複数ページに分割
    if (imgHeight <= pageHeight - margin * 2) {
      doc.addImage(imgData, 'PNG', margin, margin, imgWidth, imgHeight)
    } else {
      let remainingHeight = canvas.height
      let sourceY = 0
      const sliceHeightInCanvasPixels = ((pageHeight - margin * 2) / imgWidth) * canvas.width

      while (remainingHeight > 0) {
        if (sourceY > 0) doc.addPage()

        const currentSliceHeight = Math.min(sliceHeightInCanvasPixels, remainingHeight)
        const sliceCanvas = document.createElement('canvas')
        sliceCanvas.width = canvas.width
        sliceCanvas.height = currentSliceHeight
        const ctx = sliceCanvas.getContext('2d')!
        ctx.drawImage(canvas, 0, sourceY, canvas.width, currentSliceHeight, 0, 0, canvas.width, currentSliceHeight)

        const sliceData = sliceCanvas.toDataURL('image/png')
        const sliceImgHeight = (currentSliceHeight * imgWidth) / canvas.width
        doc.addImage(sliceData, 'PNG', margin, margin, imgWidth, sliceImgHeight)

        sourceY += currentSliceHeight
        remainingHeight -= currentSliceHeight
      }
    }

    doc.save(filename)
  } finally {
    document.body.removeChild(contentEl)
  }
}

/**
 * 作品詳細をPDF化する。
 */
export async function exportDetailPdf(work: Work): Promise<void> {
  const el = createPdfContentElement(work)
  await captureAndSavePdf(el, `${work.slug}-detail.pdf`, 'p')
}

/**
 * 比較結果をPDF化する。
 */
export async function exportComparePdf(works: Work[]): Promise<void> {
  const el = createCompareContentElement(works)
  await captureAndSavePdf(el, 'works-comparison.pdf', 'l')
}
